// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDLcghEWBwdVWkiXexOqeqawPRv8O-w0',
    appId: '1:803380758679:web:7aacc80a886aa3cf1341d2',
    messagingSenderId: '803380758679',
    projectId: 'sabaq-681b2',
    authDomain: 'sabaq-681b2.firebaseapp.com',
    storageBucket: 'sabaq-681b2.firebasestorage.app',
    measurementId: 'G-PY7CBZY197',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHPBr7UU6HhaUXAx0Gtf32ZJ9Xf1gtETQ',
    appId: '1:803380758679:android:555f7b1683fedbf41341d2',
    messagingSenderId: '803380758679',
    projectId: 'sabaq-681b2',
    storageBucket: 'sabaq-681b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTlufJgolOD70EZ6SJx9PrN_Adm4LAISM',
    appId: '1:803380758679:ios:3f5820ca9bc1da321341d2',
    messagingSenderId: '803380758679',
    projectId: 'sabaq-681b2',
    storageBucket: 'sabaq-681b2.firebasestorage.app',
    iosBundleId: 'com.example.sabaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTlufJgolOD70EZ6SJx9PrN_Adm4LAISM',
    appId: '1:803380758679:ios:3f5820ca9bc1da321341d2',
    messagingSenderId: '803380758679',
    projectId: 'sabaq-681b2',
    storageBucket: 'sabaq-681b2.firebasestorage.app',
    iosBundleId: 'com.example.sabaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdDLcghEWBwdVWkiXexOqeqawPRv8O-w0',
    appId: '1:803380758679:web:252347cdc164832f1341d2',
    messagingSenderId: '803380758679',
    projectId: 'sabaq-681b2',
    authDomain: 'sabaq-681b2.firebaseapp.com',
    storageBucket: 'sabaq-681b2.firebasestorage.app',
    measurementId: 'G-9D7FC83E4S',
  );
}
