// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOn4vaymxvttKTIN8n_gIy2q3wCJ7nCM',
    appId: '1:6149419200:web:835d0f8e756f4ddcdb3d25',
    messagingSenderId: '6149419200',
    projectId: 'madrassa-aa9e6',
    authDomain: 'madrassa-aa9e6.firebaseapp.com',
    storageBucket: 'madrassa-aa9e6.firebasestorage.app',
    measurementId: 'G-HJ3TVGTZ5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ui_S00O3ai5nS-SjAk_nxl_1fLUBhTI',
    appId: '1:6149419200:android:785d3841869b20eadb3d25',
    messagingSenderId: '6149419200',
    projectId: 'madrassa-aa9e6',
    storageBucket: 'madrassa-aa9e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyGw0iGSy2YWHPQ6PsDQgJE7vQrrRMLQ',
    appId: '1:6149419200:ios:89fcf02a8135a22adb3d25',
    messagingSenderId: '6149419200',
    projectId: 'madrassa-aa9e6',
    storageBucket: 'madrassa-aa9e6.firebasestorage.app',
    iosBundleId: 'com.example.sabaq',
  );
}
